sonar.projectKey=IgorRibeiroGuimaraes_-pos-ia-eng-devops-githuapi
sonar.organization=igorribeiroguimaraes

sonar.projectName=GitHub Data Pipeline API
sonar.projectVersion=0.1.0

# Código-fonte
sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8

# Cobertura de testes (gerada pelo pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml

# Exclusões
sonar.exclusions=**/__pycache__/**,**/*.pyc,alembic/versions/**,.venv/**
sonar.test.exclusions=tests/**

# Versão do Python
sonar.python.version=3.12
