apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-pipeline.fullname" . }}-secrets
  labels:
    {{- include "github-pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "github-pipeline.databaseUrl" . | quote }}
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
